// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Chronus","status":true,"description":"时间时钟显示系统·优","parameters":{"月ごとの日数配列":"31,29,31,30,31,30,31,31,30,31,30,31","月名配列":"Jan.,Feb.,Mar.,Apr.,May.,Jun.,Jul.,Aug.,Sep.,Oct.,Nov.,Dec.","曜日配列":"(一),(二),(三),(四),(五),(六),(日)","自然時間加算":"5","自然時間加算間隔":"60","場所移動時間加算":"30","戦闘時間加算(固定)":"30","戦闘時間加算(ターン)":"5","年のゲーム変数":"0","月のゲーム変数":"0","日のゲーム変数":"0","曜日IDのゲーム変数":"0","曜日名のゲーム変数":"0","時のゲーム変数":"0","分のゲーム変数":"0","累計時間のゲーム変数":"0","累計日数のゲーム変数":"0","時間帯IDのゲーム変数":"0","天候IDのゲーム変数":"0","フォーマット時間の変数":"0","フォーマット時間の計算式":"HH24 * 60 + MI","日時フォーマット1":"YYYY年 MM月 DD日 DY","日時フォーマット2":"AMHH点 MI分","日時フォーマット行間":"0","カレンダー表示X座標":"0","カレンダー表示Y座標":"0","カレンダーフォントサイズ":"0","カレンダー不透明度":"192","カレンダー枠の非表示":"false","カレンダーの非表示":"false","カレンダー余白":"8","文字盤画像ファイル":"","長針画像ファイル":"","短針画像ファイル":"","時計X座標":"84","時計Y座標":"156","イベント中時間経過":"false"}}
];
